apiVersion: v1
kind: Service
metadata:
  name: multiplication
  namespace: multiplication
  annotations:
    mesh.traefik.io/scheme: "h2c"
spec:
  ports:
    - name: http
      protocol: TCP
      port: 9090
      targetPort: 9090
  selector:
    app: multiplication
