apiVersion: v1
kind: Service
metadata:
  name: subtraction
  namespace: subtraction
spec:
  ports:
    - name: http
      protocol: TCP
      port: 9090
      targetPort: 9090
  selector:
    app: subtraction
